### ISSUE TITLE
The pod `web` not loaded with secret

### ISSUE THREAD

**Issue by lesmyrmidons** [AdWerx/charts#24]
Hello!!

My postgesSQL is external.

I create a secret with version 3.2.0 of chart. And the pod web not started because it is error return : 
![image](https://user-images.githubusercontent.com/1608684/123924233-0c4cb500-d98a-11eb-99c7-bbe3db0219e0.png)

If the variable progresql host is not added, it's `{{ printf "%s-postgresql" .Release.Name | b64enc | quote }}` used but not `DATABASE_HOST` of my secret.
My secret is generate with sealed-secret for bitnami :
```
sealed-secrets:
  - name: awx-secret
    data:
      AWX_ADMIN_PASSWORD:
      AWX_ADMIN_USER:
      DATABASE_ADMIN_PASSWORD:
      DATABASE_HOST:
      DATABASE_NAME:
      DATABASE_PASSWORD:
      DATABASE_PORT:
      DATABASE_USER:
      SECRET_KEY:
```
