### ISSUE TITLE
postgresqlPassword is expected even if using postgresqlExistingSecret

### ISSUE THREAD

**Issue by 2stacks** [AdWerx/charts#26]
Attempt to install latest tagged version
```
> helm install -f values.yaml awx adwerx/awx --version 3.2.1
Error: values don't meet the specifications of the schema(s) in the following chart(s):
postgresql:
- postgresqlPassword: Invalid type. Expected: string, given: null
```
Below is my values.yaml
```
USER-SUPPLIED VALUES:
defaultAdminExistingSecret: awx-admin-creds
secretKeyExistingSecret: awx-secret-key
postgresqlExistingSecret: awx-pgsql-creds
```

**Comment by jbielick** [comment]
Have you set `postgresql.enabled` to `false`?

In the values file we have:

```yaml
postgresql:
  # -- Set to false if using external postgresql
  enabled: true
```

**Comment by 2stacks** [comment]
No I was trying to use the internal DB and inject passwords with existing
secrets.  It wasn't clear from the comments/docs that this wasn't
supported.

**Comment by jbielick** [comment]
Ah, okay. It should be possible, though I haven't tried it personally.

Could you try setting `postgresql.postgresqlPassword` to an empty string? I was looking at the subchart values and it seems like they default to an empty string. If that works correctly I think this chart could default to an empty string as well.

![image](https://user-images.githubusercontent.com/1413330/129911296-37a74540-85f1-465f-8c29-93f8333145f0.png)

**Comment by gmisura** [comment]
I got it working with this in my values.yml (yaml) file

postgresql:
  volumePermissions:
    enabled: true

**Comment by 2stacks** [comment]
Awesome, I started going through the postgresql helm chart options to solve
it but you got there first.

**Comment by jbielick** [comment]
@2stacks did that work? The empty string?

**Comment by 2stacks** [comment]
I wasn't able to get it to work.  If I deploy awx and postgresql as
separate helm charts everything works fine.  I've also had success with the
new operator so I'm not going to worry too much about it.  Below is the
last values.yaml file I tried.  Everything deployed but the web container
never connected to the DB.  I had to create two separate pgsql secrets due
to different information being required.

```
defaultAdminExistingSecret: awx-admin-creds
postgresql:
  enabled: true
  postgresqlPassword: ""
  volumePermissions:
    enabled: true
  existingSecret: pgsql-creds
secretKeyExistingSecret: awx-secret-key
postgresqlExistingSecret: awx-pgsql-creds
```
I had to create two separate pgsql secrets due to different information
being required.
```
kubectl create secret generic awx-pgsql-creds \
  --from-literal=DATABASE_USER=awx \
  --from-literal=DATABASE_NAME=awx \
  --from-literal=DATABASE_HOST=postgresql \
  --from-literal=DATABASE_PORT=5432 \
  --from-literal=DATABASE_PASSWORD=test \
  --from-literal=DATABASE_ADMIN_PASSWORD=test

kubectl create secret generic pgsql-creds \
  --from-literal=postgresql-password=test \
  --from-literal=postgresql-postgres-password=test
```
